const commonTheme = {
  typography: {
    fontFamily: {
      bold: "PretendardBold",
      semibold: "PretendardSemiBold",
      medium: "PretendardMedium",
      regular: "PretendardRegular",
    },
  },
};

export const typography = {
  display1: {
    fontSize: 24,
    lineHeight: 24 * 1.4,
    letterSpacing: 24 * -0.02,
    fontWeight: "700",
    fontFamily: commonTheme.typography.fontFamily.bold,
  },
  display2: {
    fontSize: 20,
    lineHeight: 20 * 1.4,
    letterSpacing: 20 * -0.02,
    fontWeight: "700",
    fontFamily: commonTheme.typography.fontFamily.bold,
  },
  display3: {
    fontSize: 18,
    lineHeight: 18 * 1.4,
    letterSpacing: 18 * -0.02,
    fontWeight: "700",
    fontFamily: commonTheme.typography.fontFamily.bold,
  },
  display4: {
    fontSize: 16,
    lineHeight: 16 * 1.4,
    letterSpacing: 16 * -0.02,
    fontWeight: "700",
    fontFamily: commonTheme.typography.fontFamily.bold,
  },
  display5: {
    fontSize: 9,
    lineHeight: 9 * 1.3,
    letterSpacing: 9 * -0.03,
    fontWeight: "700",
    fontFamily: commonTheme.typography.fontFamily.bold,
  },
  head1: {
    fontSize: 20,
    lineHeight: 20 * 1.4,
    letterSpacing: 20 * -0.02,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  head2: {
    fontSize: 18,
    lineHeight: 18 * 1.4,
    letterSpacing: 18 * -0.02,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  body1: {
    fontSize: 16,
    lineHeight: 16 * 1.4,
    letterSpacing: 16 * -0.02,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  body2: {
    fontSize: 15,
    lineHeight: 15 * 1.3,
    letterSpacing: 15 * -0.02,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  body3: {
    fontSize: 14,
    lineHeight: 14 * 1.4,
    letterSpacing: 14 * -0.02,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  body4: {
    fontSize: 13,
    lineHeight: 13 * 1.4,
    letterSpacing: 13 * -0.02,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  body5: {
    fontSize: 12,
    lineHeight: 12 * 1.4,
    letterSpacing: 12 * -0.02,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  body6: {
    fontSize: 11,
    lineHeight: 11 * 1.3,
    letterSpacing: 11 * -0.03,
    fontWeight: "600",
    fontFamily: commonTheme.typography.fontFamily.semibold,
  },
  body7: {
    fontSize: 18,
    lineHeight: 18 * 1.4,
    letterSpacing: 18 * -0.02,
    fontWeight: "500",
    fontFamily: commonTheme.typography.fontFamily.medium,
  },
  body8: {
    fontSize: 16,
    lineHeight: 16 * 1.4,
    letterSpacing: 16 * -0.02,
    fontWeight: "500",
    fontFamily: commonTheme.typography.fontFamily.medium,
  },
  body9: {
    fontSize: 15,
    lineHeight: 15 * 1.4,
    letterSpacing: 15 * -0.02,
    fontWeight: "500",
    fontFamily: commonTheme.typography.fontFamily.medium,
  },
  body10: {
    fontSize: 14,
    lineHeight: 14 * 1.4,
    letterSpacing: 14 * -0.02,
    fontWeight: "500",
    fontFamily: commonTheme.typography.fontFamily.medium,
  },
  body11: {
    fontSize: 13,
    lineHeight: 13 * 1.4,
    letterSpacing: 13 * -0.02,
    fontWeight: "500",
    fontFamily: commonTheme.typography.fontFamily.medium,
  },
  body12: {
    fontSize: 12,
    lineHeight: 12 * 1.2,
    letterSpacing: 12 * -0.02,
    fontWeight: "500",
    fontFamily: commonTheme.typography.fontFamily.medium,
  },
  body13: {
    fontSize: 9,
    lineHeight: 9 * 1.3,
    letterSpacing: 9 * -0.03,
    fontWeight: "500",
    fontFamily: commonTheme.typography.fontFamily.medium,
  },

  caption1: {
    fontSize: 14,
    lineHeight: 14 * 1.4,
    letterSpacing: 14 * -0.02,
    fontWeight: "400",
    fontFamily: commonTheme.typography.fontFamily.regular,
  },
  caption2: {
    fontSize: 13,
    lineHeight: 13 * 1.4,
    letterSpacing: 13 * -0.02,
    fontWeight: "400",
    fontFamily: commonTheme.typography.fontFamily.regular,
  },
  caption3: {
    fontSize: 12,
    lineHeight: 12 * 1.4,
    letterSpacing: 12 * -0.02,
    fontWeight: "400",
    fontFamily: commonTheme.typography.fontFamily.regular,
  },
} as const;
